//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_LOCACION_RESPONSABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE_LOCACION_RESPONSABLE()
        {
            this.CLIENTE_LOCACION_RESPONSABLE_CONTACTO = new HashSet<CLIENTE_LOCACION_RESPONSABLE_CONTACTO>();
        }
    
        public int id { get; set; }
        public int idClienteLocacion { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public bool habilitadoPortal { get; set; }
        public string usuarioPortal { get; set; }
        public string clavePortal { get; set; }
    
        public virtual CLIENTE_LOCACION CLIENTE_LOCACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_LOCACION_RESPONSABLE_CONTACTO> CLIENTE_LOCACION_RESPONSABLE_CONTACTO { get; set; }
    }
}
