//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CLIENTE_CONTACTO = new HashSet<CLIENTE_CONTACTO>();
            this.CLIENTE_LOCACION = new HashSet<CLIENTE_LOCACION>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int id { get; set; }
        public int idDocumentoTipo { get; set; }
        public long numeroDocumento { get; set; }
        public string razonSocial { get; set; }
        public bool habitlitadoPortal { get; set; }
        public string usuarioPortal { get; set; }
        public string clavePortal { get; set; }
        public bool baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CONTACTO> CLIENTE_CONTACTO { get; set; }
        public virtual DOCUMENTO_TIPO DOCUMENTO_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_LOCACION> CLIENTE_LOCACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
