//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_LOCACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE_LOCACION()
        {
            this.CLIENTE_LOCACION_RESPONSABLE = new HashSet<CLIENTE_LOCACION_RESPONSABLE>();
            this.CLIENTE_LOCACION_SECTOR = new HashSet<CLIENTE_LOCACION_SECTOR>();
            this.ORDEN_TRABAJO = new HashSet<ORDEN_TRABAJO>();
            this.CONTROL_PLAGA = new HashSet<CONTROL_PLAGA>();
        }
    
        public int id { get; set; }
        public int idCliente { get; set; }
        public string descripcion { get; set; }
        public int idProvincia { get; set; }
        public string localidad { get; set; }
        public string calle { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> piso { get; set; }
        public string departamento { get; set; }
        public string observaciones { get; set; }
        public bool baja { get; set; }
        public int cantidadDiasCebaderas { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_LOCACION_RESPONSABLE> CLIENTE_LOCACION_RESPONSABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_LOCACION_SECTOR> CLIENTE_LOCACION_SECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO> ORDEN_TRABAJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PLAGA> CONTROL_PLAGA { get; set; }
    }
}
