//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO_TIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTO_TIPO()
        {
            this.CLIENTE_CONTACTO = new HashSet<CLIENTE_CONTACTO>();
            this.CLIENTE_LOCACION_RESPONSABLE_CONTACTO = new HashSet<CLIENTE_LOCACION_RESPONSABLE_CONTACTO>();
            this.EMPLEADO_CONTACTO = new HashSet<EMPLEADO_CONTACTO>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CONTACTO> CLIENTE_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_LOCACION_RESPONSABLE_CONTACTO> CLIENTE_LOCACION_RESPONSABLE_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_CONTACTO> EMPLEADO_CONTACTO { get; set; }
    }
}
