//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_PLAGA_DETALLE
    {
        public int id { get; set; }
        public Nullable<int> idControlPlaga { get; set; }
        public Nullable<int> idTarea { get; set; }
    
        public virtual CONTROL_PLAGA CONTROL_PLAGA { get; set; }
        public virtual TAREA TAREA { get; set; }
    }
}
