//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_CONTACTO
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public int idContactoTipo { get; set; }
        public string valor { get; set; }
        public string observaciones { get; set; }
        public bool conexionApp { get; set; }
    
        public virtual CONTACTO_TIPO CONTACTO_TIPO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
