//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAFICOS
    {
        public int id { get; set; }
        public int idTrampaTipo { get; set; }
        public string descripcion { get; set; }
        public bool otroFormatoEjeX { get; set; }
    
        public virtual TRAMPA_TIPO TRAMPA_TIPO { get; set; }
    }
}
