//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_USUARIO
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idMenu { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
