//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_TRABAJO_DETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_TRABAJO_DETALLE()
        {
            this.ORDEN_TRABAJO_DETALLE_ESTADO = new HashSet<ORDEN_TRABAJO_DETALLE_ESTADO>();
            this.ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA = new HashSet<ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA>();
        }
    
        public int id { get; set; }
        public int idOrdenTrabajo { get; set; }
        public int idTrampaClienteLocacionSector { get; set; }
        public Nullable<int> idAccion { get; set; }
        public Nullable<decimal> moscas { get; set; }
        public Nullable<decimal> mosquitas { get; set; }
        public Nullable<decimal> polillas { get; set; }
        public Nullable<decimal> mariposas { get; set; }
        public Nullable<decimal> minusculos { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> cargado { get; set; }
        public Nullable<int> roedor { get; set; }
        public Nullable<int> insecto { get; set; }
        public Nullable<int> cucaGermanica { get; set; }
        public Nullable<int> cucaAmericana { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_DETALLE_ESTADO> ORDEN_TRABAJO_DETALLE_ESTADO { get; set; }
        public virtual TRAMPA_CLIENTE_LOCACION_SECTOR TRAMPA_CLIENTE_LOCACION_SECTOR { get; set; }
        public virtual TRAMPA_CONTROL_ACCION TRAMPA_CONTROL_ACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA> ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA { get; set; }
        public virtual TRAMPA_CONTROL_ESTADO TRAMPA_CONTROL_ESTADO { get; set; }
    }
}
