//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.CONTROL_PLAGA_DETALLE = new HashSet<CONTROL_PLAGA_DETALLE>();
            this.ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA = new HashSet<ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA>();
        }
    
        public int id { get; set; }
        public int idTipoTrampa { get; set; }
        public string descripcion { get; set; }
    
        public virtual TRAMPA_TIPO TRAMPA_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PLAGA_DETALLE> CONTROL_PLAGA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA> ORDEN_TRABAJO_DETALLE_CONTROL_PLAGA { get; set; }
    }
}
