//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMPA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAMPA()
        {
            this.TRAMPA_CLIENTE_LOCACION_SECTOR = new HashSet<TRAMPA_CLIENTE_LOCACION_SECTOR>();
        }
    
        public int id { get; set; }
        public int idTrampaTipo { get; set; }
        public int idTrampaEstado { get; set; }
        public string numero { get; set; }
        public string observaciones { get; set; }
    
        public virtual TRAMPA_ESTADO TRAMPA_ESTADO { get; set; }
        public virtual TRAMPA_TIPO TRAMPA_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA_CLIENTE_LOCACION_SECTOR> TRAMPA_CLIENTE_LOCACION_SECTOR { get; set; }
    }
}
