//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMPA_TIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAMPA_TIPO()
        {
            this.CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA = new HashSet<CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA>();
            this.TRAMPA = new HashSet<TRAMPA>();
            this.TRAMPA_CONTROL_ACCION = new HashSet<TRAMPA_CONTROL_ACCION>();
            this.TRAMPA_CONTROL_ESTADO = new HashSet<TRAMPA_CONTROL_ESTADO>();
            this.GRAFICOS = new HashSet<GRAFICOS>();
            this.TAREA = new HashSet<TAREA>();
            this.CONTROL_PLAGA = new HashSet<CONTROL_PLAGA>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public bool baja { get; set; }
        public bool multiSel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA> CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA> TRAMPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA_CONTROL_ACCION> TRAMPA_CONTROL_ACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA_CONTROL_ESTADO> TRAMPA_CONTROL_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRAFICOS> GRAFICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PLAGA> CONTROL_PLAGA { get; set; }
    }
}
